-- proposal-supabase-sync / 001_init.sql
-- Feed this file into Supabase MCP `apply_migration` as the `query` arg.
-- Single-user model: no owner_id, no RLS.
-- Idempotent: safe to re-run.

-- 1) Extensions
create extension if not exists vector     with schema extensions;
create extension if not exists pg_trgm    with schema extensions;

-- 2) Storage bucket (used only if prep.py uploads via HTTP)
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('proposals', 'proposals', false, 104857600, array['application/pdf'])
on conflict (id) do nothing;

-- 3) Main table
create table if not exists public.proposals (
    id                   bigint generated by default as identity primary key,

    -- File
    storage_bucket       text,
    storage_path         text not null,
    file_name            text not null,
    file_hash            char(64) not null unique,
    file_size            bigint not null,
    page_count           int,
    mime_type            text default 'application/pdf',

    -- Business meta
    doc_type             text default '제안서',
    title                text not null,
    project_year         smallint,
    client_name          text,
    client_type          text check (client_type in ('공공','민간','지자체','기타') or client_type is null),
    industry             text,
    service_category     text[] default '{}',
    budget_krw           bigint,
    contract_period      daterange,
    submitted_at         date,

    -- AI summary
    abstract             text,
    key_points           text[] default '{}',
    objectives           text,
    strategy             text,
    deliverables         text[] default '{}',
    tags                 text[] default '{}',

    -- Search
    -- NOTE: search_tsv is populated by a trigger (not a GENERATED column).
    -- Postgres 15+ treats to_tsvector(regconfig,text) as STABLE, not IMMUTABLE,
    -- so `generated always as (...) stored` fails with 42P17 on apply_migration.
    full_text            text,
    search_tsv           tsvector,

    -- Embedding (1536-dim Matryoshka from Gemini — fits pgvector HNSW's 2000-dim cap)
    embedding            extensions.vector(1536),
    embedding_model      text,
    embedding_input_hash char(64),

    -- Audit
    created_at           timestamptz not null default now(),
    updated_at           timestamptz not null default now()
);

-- 4) Combined before-write trigger: fills search_tsv + bumps updated_at
create or replace function public.proposals_before_write() returns trigger
language plpgsql as $$
begin
  new.search_tsv :=
        setweight(to_tsvector('simple', coalesce(new.title,'')),                        'A')
     || setweight(to_tsvector('simple', coalesce(new.abstract,'')),                     'B')
     || setweight(to_tsvector('simple', array_to_string(coalesce(new.tags,'{}'),' ')),  'B')
     || setweight(to_tsvector('simple', coalesce(new.full_text,'')),                    'D');
  new.updated_at := now();
  return new;
end $$;

drop trigger if exists proposals_before_write on public.proposals;
create trigger proposals_before_write
before insert or update on public.proposals
for each row execute procedure public.proposals_before_write();

-- 5) Indexes
create index if not exists idx_proposals_tsv         on public.proposals using gin (search_tsv);
create index if not exists idx_proposals_tags        on public.proposals using gin (tags);
create index if not exists idx_proposals_cat         on public.proposals using gin (service_category);
create index if not exists idx_proposals_title_trgm  on public.proposals using gin (title extensions.gin_trgm_ops);
create index if not exists idx_proposals_client_trgm on public.proposals using gin (client_name extensions.gin_trgm_ops);
create index if not exists idx_proposals_year        on public.proposals (project_year desc);

create index if not exists idx_proposals_embedding
  on public.proposals using hnsw (embedding extensions.vector_cosine_ops)
  with (m = 16, ef_construction = 64);

-- 6) Hybrid search RPC
drop function if exists public.match_proposals(
  text, extensions.vector, int, text, text[], int, float, float
);

create or replace function public.match_proposals(
  query_text       text,
  query_embedding  extensions.vector(1536),
  filter_year_min  int    default null,
  filter_industry  text   default null,
  filter_tags      text[] default null,
  match_count      int    default 10,
  kw_weight        float  default 0.4,
  vec_weight       float  default 0.6
)
returns table (
  id              bigint,
  title           text,
  client_name     text,
  project_year    smallint,
  industry        text,
  tags            text[],
  storage_path    text,
  abstract        text,
  kw_score        real,
  vec_score       real,
  hybrid_score    real
)
language sql
stable
set search_path = public, extensions
as $$
  with scored as (
    select
      p.id, p.title, p.client_name, p.project_year, p.industry,
      p.tags, p.storage_path, p.abstract,
      case
        when query_text is null or query_text = '' then 0
        else ts_rank_cd(p.search_tsv, plainto_tsquery('simple', query_text))
      end as kw_score,
      case
        when query_embedding is null then 0
        else (1 - (p.embedding <=> query_embedding))::real
      end as vec_score
    from public.proposals p
    where
      (filter_year_min is null or p.project_year >= filter_year_min)
      and (filter_industry is null or p.industry = filter_industry)
      and (filter_tags    is null or p.tags && filter_tags)
      and (
        (query_text is null or query_text = '')
        or p.search_tsv @@ plainto_tsquery('simple', query_text)
        or query_embedding is not null
      )
  )
  select
    id, title, client_name, project_year, industry, tags,
    storage_path, abstract,
    kw_score, vec_score,
    (kw_weight * kw_score + vec_weight * vec_score)::real as hybrid_score
  from scored
  order by hybrid_score desc
  limit match_count;
$$;
